version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node

    steps:
      - checkout
      # convert variables to ssh format
      - run:
          name: Convert private key to RSA
          command: |
            ssh-keygen -t rsa -b 4096 -f $PRIVATE_KEY &&
      - run:
          name: Convert private key to RSA
          command: |
            ssh-keygen -t rsa -b 4096 -f $PUBLIC_KEY

      # Install TypeScript
      - run: sudo npm install -g typescript

      # Install project dependencies
      - run: npm install

      # Compile TypeScript source code
      - run: npm run build

      # Run tests
      - run: npm run test

      # Deploy on render
